[package]
name = "chip-8"
version = "0.1.0"
authors = ["Bryan E. Barnhart <thebryanb@hotmail.com>"]

[dependencies]
rand = "0.3"
ncurses = { version = "5", optional = true }
termion = { version = "1", optional = true }

[features]
default = ["ncurses"]
